### ISSUE TITLE
Doesn't work with Vue

### ISSUE THREAD

**Issue by arnaslix** [kossa/laradminator#1]
Hey,

something is messing up with Vue. If I initialize #app container, multi level menu, sidebar collapse, tooltips, popovers doesn't work anymore. And console doesn't show any error.

Any help?

**Comment by kossa** [comment]
Hey,

First in this project I does not include VueJs so you need to add it here : https://github.com/kossa/laradminator/blob/master/resources/assets/js/bootstrap.js

And then you can add #app or whatever you want, any question is welcome ;)

Good luck

**Comment by arnaslix** [comment]
@kossa Yes I know where to include it. I mean that if you do
`const app = new Vue({
    el: '#app',
});`
And initialize it in your html, nothing works anymore. :)

I've fixed it, so if someone runs into this, maybe I'll help them to save some time.

Basically, Vue don't load simple jquery imports. All you have to do to make it works with Vue from bootstrap.js remove all imports and in app.js do it like this:
`const app = new Vue({
    el: '#app',
    mounted() {
        require('./masonry');
        require('./charts');
        require('./popover');
        require('./scrollbar');
        require('./search');
        require('./sidebar');
        require('./skycons');
        require( './chat');
        require( './datatable');
        require( './datepicker');
        require( './email');
        require( './fullcalendar');
        require( './googleMaps');
        require( './utils');
        require( './sweetalert2');
    }
});`
When page is fully loaded, Vue will mount jquery plugins. Also in bootstrap.js I added:
`try {
    window.$ = window.jQuery = require('jquery');
    window.Popper = require('popper.js').default;
    require('bootstrap');
} catch (e) {}`

But anyway, thanks @kossa for your work, needed Administrator to work with mix. :)

**Comment by kossa** [comment]
Ahh I understand now, this in case you want to load plugin from vueJs, I agree

I'm using Vue too, but I did not test it with Adminator, thank you for the tip ;)
