### ISSUE TITLE
Page Loading Slow

### ISSUE THREAD

**Issue by thanpuia** [kossa/laradminator#107]
Hello,

I used your theme and i loved it. But the problem i face is that, even after fetching all the data from serve the page loading takes a very long time. Is there any way to make it faster or remove the loading icon?

**Comment by thanpuia** [comment]
Hello, thank you so much for your support. I was thinking for so long on how to remove rhat spinner..it was right there all along. again..thank you so much!..you made my day

**Comment by kossa** [comment]
You are welcome
