### ISSUE TITLE
Error 404 in administration

### ISSUE THREAD

**Issue by BroskaCZ** [kossa/laradminator#113]
Hello,
I managed to run Laradminator with Docker. Database, main page, login and register page works and I can register or login, but when I enter administration, it throws error 404 - Not Found. I don't see many routes in web.php. It it application error or Docker error?

Thanks a lot.

**Comment by kossa** [comment]
it's /admin not administration check this [line](https://github.com/kossa/laradminator/blob/master/config/variables.php#L33)

**Comment by BroskaCZ** [comment]
I had it right - I was in /admin. When I register and don't have administrator privileges, it heades me to 404 error. I solved it by changing priveleges for now.

**Comment by kossa** [comment]
Ahh yes, there is a [middleware](https://github.com/kossa/laradminator/blob/master/app/Http/Middleware/Role.php#L25-L27) for that
