### ISSUE TITLE
Demo site deceptive

### ISSUE THREAD

**Issue by ugintl** [kossa/laradminator#117]
When I open the demo, it says deceptive site ahead. The browser wouldn't let me visit the site.

**Comment by kossa** [comment]
Fixed, thank you

**Comment by ugintl** [comment]
@kossa Still the same. I am using firefox

**Comment by kossa** [comment]
Which URL you are using? I changed it to laradminator.kossa.one [here](https://github.com/kossa/laradminator#demo)

**Comment by ugintl** [comment]
@kossa this one worked
