### ISSUE TITLE
server.php is an IDP.ALEXA.51 Trojan

### ISSUE THREAD

**Issue by mohammadghannoumirc** [kossa/laradminator#12]
hello sir,

After successful installation and download, my antivirus popped with the following issue,

Server.php is an IDP.ALEXA.51 Trojan!

I opened server.php and there was the usual code or any SERVER.PHP in any laravel framework

**Comment by kossa** [comment]
Alright I did not change server.php I used the same as : https://github.com/laravel/laravel/blob/master/server.php
May be the antivirus problem ;)

**Comment by mohammadghannoumirc** [comment]
Yes, I think so, and I did a thorough comparison between the server.php file with any server.php file in default laravel and they are the same! 

Thank you for your prompt help :)

**Comment by kossa** [comment]
You are welcome, try linux not need for antivirus ;)
