### ISSUE TITLE
Installation problem : no styles or javascript

### ISSUE THREAD

**Issue by 12luisalmeida** [kossa/laradminator#15]
Hi, after run the commands on the installation guide I'm having this:
![screen shot 2018-08-11 at 21 14 15](https://user-images.githubusercontent.com/7284099/43995743-d489bc52-9dab-11e8-96a4-7e9441cb2b7b.png)

Any idea about what i am doing wrong?

**Comment by 12luisalmeida** [comment]
It doesn't work.
It gives me  "The requested URL /laradminator/admin was not found on this server." 
But I can acess the login page of laradminator however doesnt have a background image. if i use the test@exanple.com login i can acess dashboard but it looks as you saw in the previous image I uploaded here. Thnaks for you attention.

**Comment by 12luisalmeida** [comment]
BTW I'm using MAMP as my localhost.

**Comment by kossa** [comment]
You have to create new host and make the document root to public folder like :

![image](https://user-images.githubusercontent.com/1175584/44050387-b3d9a95c-9f2e-11e8-9bcd-16a77dec7157.png)

**Comment by 12luisalmeida** [comment]
Thanks man. Consider this solved.
