### ISSUE TITLE
Login impossible because of multiple password crypt

### ISSUE THREAD

**Issue by optiroot** [kossa/laradminator#2]
I noticed that after a user registers he gets logged in, but when he tries to login again, he gets an error even if data is correct.
This is because in [RegisterController.php](https://github.com/kossa/laradminator/blob/master/app/Http/Controllers/Auth/RegisterController.php#L68) at line 68 you use **bcrypt** on the password, but it is already used by Laravel default authentication method. This causes the password to be crypted two times.

I'm opening an issue because opening a PR just for the one line of code is exaggerated.

So the only thing to do is leaving the line as
`'password' => $data['password'],` 
without the hashing function.

**Comment by kossa** [comment]
Hello @optiroot,

Thank you for the issue, I just tried to create a new "admin" user and it works fine, for the app I used simple role middleware :https://github.com/kossa/laradminator/blob/master/app/Http/Middleware/Role.php#L25

Please try to create a new user with "admin" role and let me know ;)

**Comment by optiroot** [comment]
Hello @kossa,

thanks for answering. In fact, creating an user as admin works.
I was talking in fact when an user registers himself via /register, not when you create an user in the admin panel.
So as you say everything is correct!

But... why did it was working when an user registered via /register when I removed the **bcrypt** function? That's... strange. Ahah

**Comment by kossa** [comment]
Aha alright I found the problem.

When you create the user via the admin panel it uses `UserController@store` there is no bcrypt function, the bcrypt I added it in User.php model

But for : `RegisterController@create` there is bcrypt function and bcrypt of the Model

So you can remove the bcrypt from RegisterController@create and you are done :)

**Comment by optiroot** [comment]
Great, thanks!

So, actually the bcrypt in RegisterController@create is useless. Does it uses the User.php model like UserController@store?

**Comment by kossa** [comment]
Alright I'm using [mutator](https://laravel.com/docs/master/eloquent-mutators#defining-a-mutator)
