### ISSUE TITLE
trouble while installing laradminator

### ISSUE THREAD

**Issue by Tarekrab1990** [kossa/laradminator#21]
Salam bro, i'm facing an issue while installing laradminator on my pc, as you described very well in your installing guide, here's the message error:

`$ sudo chmod 777 storage/ -R`
`bash: sudo: command not found`

Regards.

**Comment by kossa** [comment]
On windows there is no chmod only on Linux and Mac ;)

**Comment by Tarekrab1990** [comment]
thank you so much for clearing this up for me, have a nice day :)
