### ISSUE TITLE
Sidebar link Active doesn't show dot

### ISSUE THREAD

**Issue by cgmerida** [kossa/laradminator#22]
The style the sidebar.scss has a class .active:before but it is not working.

**Comment by kossa** [comment]
I think issue on : https://github.com/puikinsh/Adminator-admin-dashboard

check this link : https://colorlib.com/polygon/adminator/calendar.html

**Comment by cgmerida** [comment]
Didn't find anything but reported the bug

**Comment by kossa** [comment]
What is the wanted result ?

**Comment by cgmerida** [comment]
The dot in the active navbar.

![dotted menu](https://user-images.githubusercontent.com/25395641/49166786-adb68a80-f2f9-11e8-8f98-43ab188ebf1f.png)

**Comment by cgmerida** [comment]
@kossa I found the problem. in the file resources/js/sidebar/index.js line 55 the filter function always returns false, if you change the return from:

 `return pattern === (window.location.pathname).substr(1);`

to 

`return pattern === window.location.href;`

the dot is already working.

**Comment by kossa** [comment]
Alright it's much better I think
