### ISSUE TITLE
e.fn.vectorMap is not a function

### ISSUE THREAD

**Issue by limuel567** [kossa/laradminator#25]
I follow all of these correctly but i got this error can you tell me how to fix it.

**Setup:**
![screenshot_41](https://user-images.githubusercontent.com/40750374/49919840-f6b63380-fee2-11e8-9072-92519aedb83e.png)

**Error:**
![screenshot_37](https://user-images.githubusercontent.com/40750374/49919771-bb1b6980-fee2-11e8-97c2-836e5835b78b.png)

**Comment by kossa** [comment]
it's something relative [ladminator](https://github.com/puikinsh/Adminator-admin-dashboard) and on my projects I remove all unuseless plugins

You can remove vectorMap from here : https://github.com/kossa/laradminator/blob/master/resources/js/bootstrap.js#L44
