### ISSUE TITLE
error after run npm run prod

### ISSUE THREAD

**Issue by elhak** [kossa/laradminator#26]
i get error like this 
![image](https://user-images.githubusercontent.com/10919301/50060937-59eae300-01cd-11e9-8e4c-5cc6f42f9c7b.png) after run npm run prod vector maps datatables is not work

**Comment by elhak** [comment]
and app.js output is like this 
![image](https://user-images.githubusercontent.com/10919301/50061073-8ce1a680-01ce-11e9-907b-e0bbca68dcac.png)

**Comment by limuel567** [comment]
https://github.com/kossa/laradminator/issues/25#issue-390535486 check this issue
