### ISSUE TITLE
Delete some functions in a login page

### ISSUE THREAD

**Issue by altax** [kossa/laradminator#3]
Hello. I'm newbie, just started learning laravel. Can you explain me a proper way to delete some functions in the /login page. I just want to left this page for login to dashboard only (admin login only). 

I want to delete functions such as remembering the password, forgetting the password and creating a new account. Sorry for the stupid question, but I guess there's no need to use them. I can just delete these files like register.blade.php and so on, but i want to know exactly how to do it properly.

**Comment by kossa** [comment]
Hello @altax,

First sorry for the delay, and second there is no stupid question ;)

To delete the useless functions, you have to remove it from the blade files, and from the route
There is a way to do it https://laracasts.com/discuss/channels/laravel/remove-register-route-from-authroutes or https://stackoverflow.com/questions/42695917/laravel-5-4-disable-register-route
