### ISSUE TITLE
Best practices for personal javascript code

### ISSUE THREAD

**Issue by mentux** [kossa/laradminator#30]
It's a question, and I do not know if this place is best to ask. So what do you think about small pieces of javascript code (such as forms ajax calls, some frontend behavior, some component-specific behavior, etc.), should be placed inside a folder like `/resources/js/utils/some-folder`? Where you put your javascript codes of this type, in time, we're not talking about VueComponents, hum?

**Comment by kossa** [comment]
Alright for my case I'm creating new folder for jquery functions,  and I compile them 

Take a look on : https://github.com/kossa/laradminator/blob/master/resources/js/select2/index.js

**Comment by mentux** [comment]
Tks @kossa, 
I found this answer https://stackoverflow.com/a/45365149/2071578 which explains exactly the concept, thank you!
