### ISSUE TITLE
Can you give us a guide to do it from scratch?

### ISSUE THREAD

**Issue by Danielmorenorios** [kossa/laradminator#31]
I want to know how to do it by my own, for future projects.

Thanks!

**Comment by kossa** [comment]
Can you give me more information ? integrate what ? and which kind of projects ?

**Comment by Danielmorenorios** [comment]
Create a video tutorial on how to integrate a webpack template step by step, thanks for answering!

**Comment by kossa** [comment]
Aha I see there is a lot of tutos on [laracast](https://laracasts.com) or youtube like : https://www.youtube.com/watch?v=9Ipu43Qo-C0 and full projects like [ecommerce](https://www.youtube.com/results?search_query=laravel+ecommerce&sp=CAISAhAD) or [social network](https://www.youtube.com/results?sp=EgIQAw%253D%253D&search_query=laravel+social+network)

I you prefer books here is a great book : https://vuejsdevelopers.com/2017/11/20/vuebnb-full-stack-laravel/

**Comment by Danielmorenorios** [comment]
My concern is :

Instead of following the steps of the video, you copied the files that we need to the path "resources / js"; You also put all the dependencies that we need in the package.json file and created a .js file where you imported the necessary js files like " import './masonry'; ".

p.d: you also made a webpackConfig in laravel mix, it would be great to know how it works

Thanks for asnwering! and if i write something weird or bad pleases tell me. My grammar in english is poor.

**Comment by Danielmorenorios** [comment]
I tried to do that too but i cant have all the functionality, idk if is because i dont know how to use the mix.webpackconfig or  just is a js file that i need to import

**Comment by Danielmorenorios** [comment]
btw if you know about a good book or video tutorial about laravel please let me know (beginner to expert)

**Comment by kossa** [comment]
For video tutorial i suggest you to use laracast.com or udemy.com
