### ISSUE TITLE
Help me to integrate the template Adminator-HTML5-Admin to Laravel

### ISSUE THREAD

**Issue by wahington** [kossa/laradminator#35]
Good afternoon, I have problems to integrate the template Adminator-HTML5, your example has access to the database, it would help me to integrate only the template, I want to start from scratch, I would appreciate it a lot.

**Comment by kossa** [comment]
Hello,


Sorry for the delay, here is a great playlist : https://www.youtube.com/watch?v=-t7oMHzIpBQ&list=PLLUtELdNs2ZY5drPxIWzpq5crhantlzp7
