### ISSUE TITLE
Datatable use server side pagination?

### ISSUE THREAD

**Issue by joehannouch** [kossa/laradminator#39]
What's the best way to integrate Datatable server side.
The problem is that i'm not able to write jquery on the blade page, and i'm not able to add the jquery in the resources/js since the ajax points to a route.

tried using yarjabox

Any help is appreciated.

**Comment by kossa** [comment]
Sure, You can install yarjabox for JS, it's very easy just update this file as a jQuery code : https://github.com/kossa/laradminator/blob/master/resources/js/datatable/index.js#L5

Dont forget to compile your assets, or start a watcher

Good luck
