### ISSUE TITLE
Tutorial & Laravel 5

### ISSUE THREAD

**Issue by gunzino** [kossa/laradminator#4]
Hello,

Thank you for a great contribution. However, I am starting long-term project so I am forced to use laravel 5.5.

I would welcome if you could create such a version or at least if you can post a tutorial how to implement adminator theme to laravel.

**Comment by kossa** [comment]
Hello,

Thank you for interesting into Laradminato, for the version of laravel you can just change [composer.json](https://github.com/kossa/laradminator/blob/master/composer.json#L12) and you put any Laravel version you want, there is not relation btw Laravel and the CSS/JS

For tutorial, there is a lot of on youtube :)
https://www.youtube.com/results?search_query=create+admin+dash+laravel&page=&utm_source=opensearch
