### ISSUE TITLE
Laravel 6.0.3 Class Form not found

### ISSUE THREAD

**Issue by LebToki** [kossa/laradminator#45]
for some reason commenting out 

  require_once base_path('resources/macros/form.php');
        Schema::defaultStringLength(191);

on Learavel 6.0.3 bring up the themed Authentication pages but doesn't redirect the user to the dashboard and same goes for the .users route too.

Keeping them however doesn;t work

**Comment by kossa** [comment]
Why you want to comment those lines ?

I updated Laravel to 6.0.4 and works fine
![image](https://user-images.githubusercontent.com/1175584/65592639-dbef1000-df86-11e9-8745-6ce48ae674ca.png)
