### ISSUE TITLE
Can't access admin url

### ISSUE THREAD

**Issue by waiyan112** [kossa/laradminator#48]
In this release  can't access admin route.
127.0.0.1 is ok.
127.0.0.1/admin ( 404)

Don't show any errors.
I can see only 404 not found.
I have done these steps.

git clone https://github.com/kossa/laradminator.git

cd laradminator

composer install # Install backend dependencies

sudo chmod 777 storage/ -R # Chmod Storage

php artisan storage:link # Enable link to storage

cp .env.example .env # Update database credentials configuration

php artisan key:generate # Generate new keys for Laravel

php artisan migrate:fresh --seed # Run migration and seed users and categories for testing

yarn install # or npm i to Install node dependencies(>= node 9.x)

npm run production # To compile assets for prod

**Comment by waiyan112** [comment]
Sorry My false.

**Comment by kossa** [comment]
I think you forgot the port in the url :)
