### ISSUE TITLE
Favicon Error and npm run dev not working

### ISSUE THREAD

**Issue by deyvsonaguiar** [kossa/laradminator#5]
Hello, thanks for the programming. 

I don't understan why my favicon no working, How to show it?

I try on views in default.blade.php:

<link rel="shortcut icon" href="{{url('assets/favicon.ico')}}">

but don't working. I have too an errors in my commands 'npm run dev':

**Comment by kossa** [comment]
For favicon my be problem with cache or the path

For npm run dev, what's the node, npm version are you using ?

**Comment by deyvsonaguiar** [comment]
Hello, tranks, but I solved run "npm install". I'm using with success!

**Comment by mohammadghannoumirc** [comment]
hello sir, 

After successful installation and download, my antivirus popped with the following issue, 

Server.php is an IDP.ALEXA.51 Trojan! 

I opened server.php and there was the usual code or any SERVER.PHP in any laravel framework

**Comment by kossa** [comment]
Really I dont know how to help you !!!

![image](https://user-images.githubusercontent.com/1175584/42413912-7f7b7394-8222-11e8-99f4-8a3ad70cec89.png)

And here is the file, dont forget to run : `npm run prod`

![image](https://user-images.githubusercontent.com/1175584/42413919-a0d25328-8222-11e8-8932-f08174100b76.png)
