### ISSUE TITLE
Can't reach /admin

### ISSUE THREAD

**Issue by titoshadow** [kossa/laradminator#50]
I've seen some issue like this, but I've double checked to follow the steps and use proper URL
http://localhost:8000/ is OK
http://localhost:8000/admin 404

git clone https://github.com/kossa/laradminator.git

cd laradminator

composer install # Install backend dependencies

sudo chmod 777 storage/ -R 

php artisan storage:link

cp .env.example .env 

php artisan key:generate 

php artisan migrate:fresh --seed 

yarn install

npm run production

php artisan serve

**Comment by kossa** [comment]
i reinstallated the project, it works fine

Try to change the port : php artisan serve --port=8881

**Comment by titoshadow** [comment]
I actually used php artisan serve --host 0.0.0.0 --port=8000, but since its a Vagrant instance I'm building from scratch to test it completely

**Comment by kossa** [comment]
Alright, I never tested it in vagrant, but I never had this problem before

**Comment by titoshadow** [comment]
Okey, successfully tested in a fresh environment, so will try to sort it out by myself :) 

If solved, will update in a new issue,
Thanks !

**Comment by kossa** [comment]
Great thank you :)

**Comment by titoshadow** [comment]
Good news, demo works out of the box

Bad news, I'm unable to reproduce what happened to fail

Thanks anyway and sorry ;)

**Comment by kossa** [comment]
lol, never mind, finally it works fine ;)
