### ISSUE TITLE
Element creation

### ISSUE THREAD

**Issue by titoshadow** [kossa/laradminator#51]
I know this is kinda demo, but should item creation work out of the box ?

I'm not sure if I broke something or there is no element creation form, since the only "form" blade needs to receive an -item-, so looks not suitable to create new ones.

**Comment by kossa** [comment]
Really I didn't understand what you meant, if you want the app without data, just avoid - -seed in migration

**Comment by titoshadow** [comment]
I'm talking about adding new users (or anything based on vanilla blades you have), for example
Form blade works okey with edition, but adding or creating new elements fails

**Comment by kossa** [comment]
I checked on my server : https://laradminator.bel4.com/admin/users, it works fine 


![image](https://user-images.githubusercontent.com/1175584/69609018-e8482580-1028-11ea-9e51-64d5566f75d3.png)

![image](https://user-images.githubusercontent.com/1175584/69609043-f433e780-1028-11ea-9f6a-dc8d419730ff.png)

**Comment by titoshadow** [comment]
Got it, I'm filling the fields when editing, so once again its my fault, thanks !

I'm working in Spanish and English translation, will try to pull request if you are interested :)

**Comment by kossa** [comment]
LOL no problem, sur I'm open for any language :)

Currently I added 3 languages : https://github.com/kossa/laradminator/tree/master/resources/lang

I only need : https://github.com/kossa/laradminator/blob/master/resources/lang/en/app.php

For the rest it exists here : https://github.com/caouecs/Laravel-lang/tree/master/src/es

**Comment by titoshadow** [comment]
Wonderful !
I've got something like that from caouecs but quite a bit more developed for my use case
