### ISSUE TITLE
Active dot at sidebar looks not working

### ISSUE THREAD

**Issue by titoshadow** [kossa/laradminator#52]
As in #22, the blue dot is not showing up

This line looks guilty:
    <a class="sidebar-link {{ Str::startsWith($route, ADMIN . '.dash') ? 'active' : '' }}"

It's always evaluating to ' ', although if we "dd" it here:
@php
    $r = \Route::current()->getAction();
    $route = (isset($r['as'])) ? $r['as'] : '';
@endphp

It yelds "active" correctly

**Comment by kossa** [comment]
Alright, fixed :)
