### ISSUE TITLE
Choosing selected value in select2 <select>

### ISSUE THREAD

**Issue by titoshadow** [kossa/laradminator#53]
When building a selector with:

`{!! Form::mySelect('contact_id', 'Contact', ([0 => 'Pick one...', $contacts]), 0, ['class' => 'form-control select2']) !!}`
It does not point to the proper selector value (0, in this case, "Nothing").

I'm prepending a "0" value to my options with that array declaration, so the user is able to "deselect" a contact when picking it (maybe there is another, cleaner way :D)

If I use "form-control select" instead of the "select2" one, the option 0 I've chosen in mySelect shows up, but when using select2, the select option points to the first element I've passed to the view.

Changing method call to:
`{!! Form::mySelect('contact_id', 'Contact', ([0 => 'Nothing', $contacts]), [0 => 'Nothing'], ['class' => 'form-control select2']) !!}`
made it work as expected ... But kinda weird at displaying (that "1" should not be there?)
![imagen](https://user-images.githubusercontent.com/8121774/69804689-69e1b400-11df-11ea-9540-f0081efa5451.png)

Guess I am not using "children" properly :(

**Comment by titoshadow** [comment]
Looks solved using "prepend" from Laravel collections, in this way:

`                    {!! Form::mySelect('contact_id', 'Contact', $contacts -> prepend('Pick one...'), 0, ['class' => 'form-control select2']) !!}
`

**Comment by kossa** [comment]
I use :
```
{!! Form::mySelect('contact_id', 'Contact', [0 => 'please choose  a user'] +  App\User::pluck('name', 'id')->toArray(), 0, ['class' => 'form-control select2']) !!}
```

**Comment by titoshadow** [comment]
Yes, I think its equivalent to what I used, since I pluck in controller and pass the $contacts collection through compact, without needing toArray()

**Comment by kossa** [comment]
ahh ok I understand so it's the same, I dont like to pass it from
controller, sometimes I use the same form in different controller/view :)
