### ISSUE TITLE
Best practice to dynamically add form fields

### ISSUE THREAD

**Issue by titoshadow** [kossa/laradminator#54]
I plan to do some sort of "Order building" form, thus my users will add products to an order ... I would like to know how would you do this with laradminator, or if you know some other project which covers this matter

**Comment by kossa** [comment]
I did in frontend I mean website not in Admin, using vuejs

**Comment by titoshadow** [comment]
Yeah, but isn't it deactivated in this project?
I would like to make it here, I'm afraid :)

**Comment by kossa** [comment]
No, you can create new routes, views...

**Comment by titoshadow** [comment]
Will work with vue, thanks !
