### ISSUE TITLE
Hiding columns from datatable (while still searchable)

### ISSUE THREAD

**Issue by titoshadow** [kossa/laradminator#56]
Hi !

Have you tried to hide a column in some datatable ?

My goal is to allow searching by that "column" in the datatable search field, but dont show that column, but not sure how to achieve this.

**Comment by kossa** [comment]
The best one I now how well integrated datatable in laradminator, is @salim114

**Comment by titoshadow** [comment]
For now, I've achieved the behaviour I was looking for, just making smthin like: 

let $holdersTable = $('.holders-table').DataTable();
$holdersTable.columns([1, 2, 3]).visible(false);

But that has to be written in datatable/index.js, which looks dirty to me ..
Maybe @salim114 can light this up :)

**Comment by salim114** [comment]
Hi @titoshadow ,
I was very busy i couldn't answer you sorry mate !
Ok just follow this :
1 - go "C:\xampp\htdocs\laradminator\resources\js\datatable\index.js"
2 - under this "import 'datatables';" add this two lines :
   import 'datatables/media/css/jquery.dataTables.min.css';
   import 'datatables/media/js/jquery.dataTables.min.js';
3 - after "aaSorting: [] });" add this "$('#dataTable').DataTable().columns( [1,2] ).visible( false );"
4 - so you will have this :
import * as $ from 'jquery';
import 'datatables';
import 'datatables/media/css/jquery.dataTables.min.css';
import 'datatables/media/js/jquery.dataTables.min.js';
export default (function () {
  $('#dataTable').DataTable({ 	
		language: {
			// 'url' : 'https://cdn.datatables.net/plug-ins/1.10.16/i18n/French.json'
			// More languages : http://www.datatables.net/plug-ins/i18n/
		},		
		aaSorting: []
	});
 $('#dataTable').DataTable().columns( [1,2] ).visible( false );
}());
4 - run "npm run dev"
N.B. : each time you modify "C:\xampp\htdocs\laradminator\resources\js\datatable\index.js" you have to run "npm run dev"
if you need any thing else please do not hesitate to call me

**Comment by titoshadow** [comment]
HI @salim114, thanks for your answer !

I'm not sure if missing smthing, but I don't find the difference between what we both said.

I mean, without importing that two additional libraries I was able to select #dataTable in index.js

What I'm not able to is to select each dataTable of each form I have (from the form.blade.php file with <script> tags), neither hide any of its columns.

The solution you comment looks the same I did, selecting the tables from the datatables/index.js, yet with classes in my case.

**Comment by salim114** [comment]
Ok, if i understand u, you wont this : 
1- write your script inside "form.blade.php"
2- You have column A, B and C, if column A hold the name Tito and Salim and Kouc
3- You wont to hide column A but if you search for Tito you will be able to see column B and C belonging to Tito 
4- is it your issue  !?

**Comment by titoshadow** [comment]
Although the 1 is not mandatory (indeed I'm not sure its even correct), yes !

**Comment by salim114** [comment]
All right so : 
1- "hiding columns" you already solve it 
2- write script inside "form.blade.php" i have tried to do so before like you but i haven't reached my aim and i've tried à lot of gymnastic move but i found  my self going to colapse all the initial code so what's the deal if you can realize the same resulte in different way.
Any way i wished i can help you i'm sorry mate

**Comment by titoshadow** [comment]
Okey then I will stick with the database/index.js editions, for now
Thanks !
