### ISSUE TITLE
Unauthenticated error when multiple users login from same browser

### ISSUE THREAD

**Issue by tinyCoder32** [kossa/laradminator#57]
I'm having a really strange issue with Laravel 6, in a fresh installation of laradminator, if a user logs in to the app and logs out, then another user logs in from the same browser, I get "Unauthenticated" error for Ajax requests in the dashboard page as the user seems to be logged out, if I refresh the page the user is redirected to login page again.

The weird thing is that we stay unable to login for a while (30m or so) even from other computers, and then later the second user can login again.

What I tried:

- Changing session driver between file and database, same issue.
- Reinstalling a fresh version of Laravel 6, same issue.
- Changing PHP version between several versions > 7.2, same issue.
- Uploaded the project to 3 different servers and the issue persisted.
- Played with session timeout..
- Always cleaning project caches, browser caches, always unable to login.
- I assume that there is something related to sessions, but I couldn't find it. I appreciate your help guys.

.env
SESSION_DRIVER=file
SESSION_LIFETIME=120

I also [posted in laracasts](https://laracasts.com/discuss/channels/laravel/unauthenticated-error-when-multiple-users-login-from-same-browser) and we talked a lot about it, but i'm still unable to fix the problem.

I appreciate your advice.

**Comment by kossa** [comment]
You mean login/logout via browser, then login via ajax ?

**Comment by tinyCoder32** [comment]
No, i'm using the normal login/logout methods.
But if I use file or database as session server, I'm unable to login after i logout, the system will always log me out immediately after login.

I changed to Cookie recently, it is a bad fix, but it works.

**Comment by kossa** [comment]
I tried it works fine, may be i did not followed exactly your steps, Please can you make a video on youtube ?

**Comment by tinyCoder32** [comment]
Sorry that it is difficult now to re-create the issue because the application is in production state.

I spent about a month around this case and it is still a mystery to me.

**Comment by kossa** [comment]
So you fixed the issue?

**Comment by tinyCoder32** [comment]
No, I switched the session driver to Cookie, i had problems with the cookie length issues where the server sometimes throw errors, then i had to change the allowed length to avoid it. But the problem remains, the details on the laracast link above.

**Comment by kossa** [comment]
You are welcome bro :) 
Seems like this issue not related to Laradminator but to Laravel, so I'll close this ;)
