### ISSUE TITLE
Translation of datatable no working

### ISSUE THREAD

**Issue by deyvsonaguiar** [kossa/laradminator#6]
I'm new to laravel, and this is my first project. Thank you for being part of it by helping me with this template.
But I have not yet figured out how to translate as datatable to pt-br.
I want to use this plugin,
https://cdn.datatables.net/plug-ins/1.10.12/i18n/Portuguese-Brasil.json
how can I implement it within the project?

**Comment by kossa** [comment]
Change this line : https://github.com/kossa/laradminator/blob/master/resources/assets/js/datatable/index.js#L5

To :
```
$('#dataTable').DataTable({
		language: {
			'url' : 'https://cdn.datatables.net/plug-ins/1.10.12/i18n/Portuguese-Brasil.json'
		},
	});
```

**Comment by kossa** [comment]
Dont forget to re-run : `npm run prod`

**Comment by deyvsonaguiar** [comment]
Hello big Kossa, 

Not working: 

I paste the code for two ways resources\assets\js\datatable\index.js and resources\assets\js\admin\datatable\index.js but don't working same no 'npm run dev' or 'prod'. 

This is my code after changes: 

import * as $ from 'jquery';
import 'datatables';

export default (function () {
    $('#dataTable').DataTable({
        language: {
            'url': 'https://cdn.datatables.net/plug-ins/1.10.12/i18n/Portuguese-Brasil.json'
        },
    });

**Comment by kossa** [comment]
It works fine
![image](https://user-images.githubusercontent.com/1175584/41580542-25ec8f54-7393-11e8-878d-2ab26f54c441.png)

You have an error at the end of the file here is the full file, juste copy/paste:

```
import * as $ from 'jquery';
import 'datatables';

export default (function () {
  $('#dataTable').DataTable({
		language: {
			'url': 'https://cdn.datatables.net/plug-ins/1.10.12/i18n/Portuguese-Brasil.json'
			// More languages : http://www.datatables.net/plug-ins/i18n/
		},
		aaSorting: []
	});
}());

```

**Comment by paulortoledo** [comment]
Alguém pode colocar o código inteiro de uma página dessa em português??
