### ISSUE TITLE
Custom javascript code

### ISSUE THREAD

**Issue by titoshadow** [kossa/laradminator#60]
Hello,

I've been checking other issues about including custom javascript functions, but still have not found one (nor an answer) close enough to my case.

I am trying to add a button that has to "refresh" or redraw my ajax datatable, which reads some filters to modify the call and filter info server-side.

However, I can't figure out where to put my JS code, since I need to listen for a click on the button which is in the blade, and launch again an ajax call which is defined in datatables/index.js

Probably I'm not understanding the current JS compiling scheme, but I guess I will be facing this trouble when trying to edit the DataTable ajax calls with "data" element, which I will have to load from blade controlls (datepickers, filters...), and I think I won't be able to "see" them.

Thanks !

**Comment by kossa** [comment]
Hello,

For this you can use directly datatables/index.js, and compile it, for my case when I need something  like helpers, I create new file called helper/index.php, and I load it in bootstrap.js.

For the structure I had the same issue like you, but at the end it's an awesome structure, based on adminator :  https://github.com/puikinsh/Adminator-admin-dashboard/tree/master/src/assets/scripts

**Comment by titoshadow** [comment]
Hi, 

Completely agreed: it's an awesome structure, really cool !

Your suggestion worked like a charm, I dont know why I was pretty sure to have tested it yesterday and not getting it to work :\ weird

As always, thanks !

**Comment by kossa** [comment]
Lol, great, happy for you
