### ISSUE TITLE
The demo cannot be show the admin route

### ISSUE THREAD

**Issue by Atiladanvi** [kossa/laradminator#65]
![image](https://user-images.githubusercontent.com/11599205/80979623-f8e1a080-8dfd-11ea-8e76-52470ad634c7.png)

**Comment by kossa** [comment]
Which user you try ?
Try with : test@example.com/123456

**Comment by Atiladanvi** [comment]
> [test@example.com](mailto:test@example.com)/123456

i try: atila.danvi@outlook.com

**Comment by Atiladanvi** [comment]
> Which user you try ?
> Try with : [test@example.com](mailto:test@example.com)/123456

The news users can be acces the dash ?

**Comment by kossa** [comment]
Yes sure for security I added a middleware named `[Role](https://github.com/kossa/laradminator/blob/master/app/Http/Middleware/Role.php)` and in `[web.php](https://github.com/kossa/laradminator/blob/master/routes/web.php#L11)` I protect the dash :)

If you want to give access to user just change his [role](https://github.com/kossa/laradminator/blob/master/database/migrations/2014_10_12_000000_create_users_table.php#L23) or in the admin specify his role :

![image](https://user-images.githubusercontent.com/1175584/81330147-973c6300-9097-11ea-80b5-881b8753e1ae.png)

**Comment by Atiladanvi** [comment]
Nice ! Great !
